import { useEffect, useRef, useState } from 'react';
import { Check, ChevronLeft, Download, FileJson, FileText, LayoutDashboard, Menu, Minus, Palette, Plus, Search, Upload, UserRound, X } from 'lucide-react';
import { CVDocument } from './components/preview/CVDocument';
import { Editor } from './components/editor/Editor';
import { sampleCV } from './data/sampleCV';
import { loadProfiles, removeProfile, saveProfile } from './lib/db';
import { importCV, type ImportResult } from './lib/importCV';
import { useCVStore } from './store/useCVStore';
import type { CVData, SectionKey } from './types/cv';

const sectionLinks: { key: SectionKey | 'personal'; label: string }[] = [
  { key:'personal', label:'Personal details' }, { key:'summary', label:'Professional summary' }, { key:'location', label:'Location' },
  { key:'experiences', label:'Work experience' }, { key:'education', label:'Education' }, { key:'certifications', label:'Certifications' },
  { key:'skills', label:'Skills' }, { key:'projects', label:'Projects' }, { key:'hobbies', label:'Hobbies' }, { key:'references', label:'References' },
];

export default function App() {
  const { cv, profiles, activeSection, saveState, setCV, setProfiles, setActiveSection, setSaveState, update } = useCVStore();
  const [screen,setScreen] = useState<'landing'|'dashboard'|'builder'>('landing');
  const [mobileTab,setMobileTab] = useState<'edit'|'preview'|'theme'>('edit');
  const [zoom,setZoom] = useState(.75); const [pages,setPages]=useState(1); const [menu,setMenu]=useState(false); const [search,setSearch]=useState('');
  const [review,setReview]=useState<ImportResult|null>(null); const uploadRef=useRef<HTMLInputElement>(null); const jsonRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{ loadProfiles().then((items)=>{ if(items.length){setProfiles(items);setCV(items[0]);setScreen('dashboard')} }).catch(()=>setSaveState('error')); },[setCV,setProfiles,setSaveState]);
  useEffect(()=>{ if(saveState!=='saving')return; const timer=setTimeout(()=>saveProfile(cv).then(async()=>{setSaveState('saved');setProfiles(await loadProfiles())}).catch(()=>setSaveState('error')),450); return()=>clearTimeout(timer); },[cv,saveState,setProfiles,setSaveState]);

  const create = () => { const next=structuredClone(sampleCV); next.id=crypto.randomUUID(); next.profileName='Untitled CV'; next.updatedAt=new Date().toISOString(); setCV(next); setSaveState('saving'); setScreen('builder'); };
  const duplicate = (profile:CVData) => { const next=structuredClone(profile);next.id=crypto.randomUUID();next.profileName=`${profile.profileName} — Copy`;next.updatedAt=new Date().toISOString();setCV(next);setSaveState('saving');setScreen('builder'); };
  const onUpload=async(file?:File)=>{if(!file)return;try{setReview(await importCV(file,cv));}catch(error){alert(`Could not read this document: ${error instanceof Error?error.message:'Unknown error'}`)}};
  const acceptImport=()=>{if(!review)return;setCV(review.draft);setSaveState('saving');setReview(null);setScreen('builder')};
  const exportJson=()=>download(new Blob([JSON.stringify(cv,null,2)],{type:'application/json'}),'cv-profile.json');
  const importJson=async(file?:File)=>{if(!file)return;try{const parsed=JSON.parse(await file.text()) as CVData;if(parsed.schemaVersion!==1)throw new Error('Unsupported schema version');setCV({...parsed,id:crypto.randomUUID(),updatedAt:new Date().toISOString()});setSaveState('saving')}catch(e){alert(e instanceof Error?e.message:'Invalid profile')}};
  const print=()=>{document.title=`${cv.settings.fileName||cv.personal.fullName.replaceAll(' ','_')+'_CV'}`;window.print()};

  if(screen==='landing') return <main className="landing"><div className="brand"><Logo/>Classic Blue</div><div className="hero"><span>LAYOUT-LOCKED CV BUILDER</span><h1>Your CV, without redesigning it every time.</h1><p>Update your experience, skills and achievements. Your polished layout takes care of itself.</p><div><button className="primary large" onClick={create}>Create CV <Plus/></button><button className="secondary large" onClick={()=>uploadRef.current?.click()}>Upload existing CV <Upload/></button></div><small>Private by design · Your data stays in this browser</small></div><input ref={uploadRef} hidden type="file" accept=".pdf,.docx" onChange={(e)=>onUpload(e.target.files?.[0])}/>{review&&<ImportReview result={review} onCancel={()=>setReview(null)} onAccept={acceptImport}/>}</main>;
  if(screen==='dashboard') return <main className="dashboard"><DashboardHeader onBuilder={()=>setScreen('builder')}/><div className="dashboard-content"><div className="dash-title"><div><p>Good afternoon</p><h1>My CVs</h1></div><div className="dash-actions"><button className="secondary" onClick={()=>uploadRef.current?.click()}><Upload/>Upload CV</button><button className="primary" onClick={create}><Plus/>New CV</button></div></div><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search profiles, roles, or skills"/></label><div className="profile-grid">{profiles.filter(p=>JSON.stringify(p).toLowerCase().includes(search.toLowerCase())).map(profile=><article className="profile-card" key={profile.id}><div className="mini-page"><span>JG</span></div><div><h2>{profile.profileName}</h2><p>Updated {relative(profile.updatedAt)}</p><span>Classic Blue</span></div><div className="profile-actions"><button onClick={()=>{setCV(profile);setScreen('builder')}}>Open</button><button onClick={()=>duplicate(profile)}>Duplicate</button><button className="danger" onClick={async()=>{if(confirm('Delete this CV? This cannot be undone.')){await removeProfile(profile.id);setProfiles(await loadProfiles())}}}>Delete</button></div></article>)}</div></div><input ref={uploadRef} hidden type="file" accept=".pdf,.docx" onChange={(e)=>onUpload(e.target.files?.[0])}/>{review&&<ImportReview result={review} onCancel={()=>setReview(null)} onAccept={acceptImport}/>}</main>;
  return <div className="app">
    <header className="topbar app-ui"><button className="icon-button mobile-only" onClick={()=>setMenu(!menu)} aria-label="Open navigation"><Menu/></button><button className="brand-button" onClick={()=>setScreen('dashboard')}><Logo/><span>Classic Blue</span></button><div className="document-name"><input aria-label="CV name" value={cv.profileName} onChange={e=>update(c=>{c.profileName=e.target.value})}/><span className={`save ${saveState}`}>{saveState==='saved'?<Check/>:null}{saveState==='saving'?'Saving…':saveState==='saved'?'Saved':'Unable to save'}</span></div><div className="top-actions"><button onClick={exportJson}><FileJson/>Export profile</button><button onClick={()=>jsonRef.current?.click()}><Upload/>Import profile</button><button className="primary" onClick={print}><Download/>Download PDF</button></div><input ref={jsonRef} hidden type="file" accept="application/json" onChange={e=>importJson(e.target.files?.[0])}/></header>
    <div className="mobile-tabs app-ui"><button className={mobileTab==='edit'?'active':''} onClick={()=>setMobileTab('edit')}>Edit</button><button className={mobileTab==='preview'?'active':''} onClick={()=>setMobileTab('preview')}>Preview</button><button className={mobileTab==='theme'?'active':''} onClick={()=>{setMobileTab('theme');setActiveSection('theme')}}>Theme</button></div>
    <div className="workspace">
      <aside className={`sidebar app-ui ${menu?'open':''}`}><div className="sidebar-head"><span>CONTENT</span><button className="icon-button mobile-only" onClick={()=>setMenu(false)}><X/></button></div><nav>{sectionLinks.map(item=><button key={item.key} className={activeSection===item.key?'active':''} onClick={()=>{setActiveSection(item.key);setMenu(false)}}>{item.label}<span>{count(cv,item.key)}</span></button>)}</nav><div className="sidebar-bottom"><button className={activeSection==='sections'?'active':''} onClick={()=>setActiveSection('sections')}><LayoutDashboard/>Sections</button><button className={activeSection==='theme'?'active':''} onClick={()=>setActiveSection('theme')}><Palette/>Theme & layout</button></div></aside>
      <section className={`editor-pane app-ui mobile-${mobileTab}`}><Editor/></section>
      <section className={`preview-pane mobile-${mobileTab}`}><div className="preview-toolbar app-ui"><div className="zoom"><button onClick={()=>setZoom(Math.max(.5,zoom-.15))}><Minus/></button><button className="zoom-value" onClick={()=>setZoom(.75)}>{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(Math.min(1.25,zoom+.15))}><Plus/></button></div><strong>{pages} {pages===1?'Page':'Pages'}</strong>{pages>4&&<span className="page-warning">Consider Compact spacing</span>}<button className="primary" onClick={print}><Download/>Download PDF</button></div><div className="preview-scroll"><CVDocument cv={cv} zoom={zoom} onPageCount={setPages}/></div></section>
    </div>
  </div>;
}

function Logo(){return <span className="logo"><FileText/></span>}
function DashboardHeader({onBuilder}:{onBuilder:()=>void}){return <header className="dashboard-header"><div className="brand"><Logo/>Classic Blue</div><button onClick={onBuilder}>Open editor</button><div className="avatar">JG</div></header>}
function ImportReview({result,onCancel,onAccept}:{result:ImportResult;onCancel:()=>void;onAccept:()=>void}){return <div className="modal-backdrop"><section className="import-modal"><button className="modal-close" onClick={onCancel}><X/></button><span className="eyebrow">IMPORT REVIEW</span><h2>We found the following information</h2><p>Nothing will replace your profile until you accept it.</p><div className="detected"><label>Name<input value={result.draft.personal.fullName} onChange={e=>result.draft.personal.fullName=e.target.value}/></label><label>Email<input value={result.draft.personal.email} onChange={e=>result.draft.personal.email=e.target.value}/></label><label>Phone<input value={result.draft.personal.phone} onChange={e=>result.draft.personal.phone=e.target.value}/></label></div><div className="warnings">{result.warnings.map(w=><p key={w}>Review needed · {w}</p>)}</div><details><summary>Extracted text</summary><pre>{result.text.slice(0,5000)}</pre></details><div className="modal-actions"><button onClick={onCancel}>Cancel</button><button className="primary" onClick={onAccept}>Accept and edit</button></div></section></div>}
function count(cv:CVData,key:string){const value=cv[key as keyof CVData];return Array.isArray(value)?value.length:''}
function download(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function relative(date:string){const hours=Math.floor((Date.now()-new Date(date).getTime())/36e5);if(hours<1)return 'just now';if(hours<24)return `${hours}h ago`;const days=Math.floor(hours/24);return days===1?'yesterday':`${days} days ago`}
